# Generated by Django 6.1.1 on 2026-09-29 16:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packing.product')),
            ],
        ),
    ]
